### ISSUE TITLE
Add "resources" to mentors and attendees

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#1]
Can we add a "resources" tab for both startups and mentors? Ideally we would edit this from the admin side and paste useful links (think speaker decks, forms, photo album links, etc.), which would need to be different for each group (mentors and startups)

**Comment by greenido** [comment]
Good idea.
We can talk about it for the next version(s).

**Comment by joshyellin** [comment]
Ok, sounds good. We used a defjam site for this last time, but I'd love to get everything on the app (eventually). Next version sgtm.

**Comment by greenido** [comment]
Btw, you do have the option to add both startups and mentors all the links you wish in their 'comments' field. So it's a solution for the short term.

**Comment by joshyellin** [comment]
Ok, noted, although not ideal as these resources will apply to all members of a particular group (MENTORS or ATTENDEES).

Not a big deal though as I can create a simple defjam site like last time for this if need be, but would be much more desirable to keep it all on app.

**Comment by joshyellin** [comment]
Let's discuss this... I think it wouldn't be hard to add, and would love to have it for V1. If we can do this, we can avoid the defjam site altogether.

**Comment by greenido** [comment]
Please add here an example to such 'resources' note.

**Comment by joshyellin** [comment]
Check the [defjam site from bootcamp 1](https://events.withgoogle.com/bootcamp1/resources-for-mentors/) to get what I mean. It would house links to speaker decks, forms, etc.

**Comment by greenido** [comment]
OK - I see what is the need here.
1. For the attendees you have the option today to put all the details in the 'daily' comments that they see in the top of their schedule.
2. As for the mentors - I'll create something if I will have time for V1.

**Comment by greenido** [comment]
You can now do it by using the 'comments for the day' both to mentors and attendees.
