### ISSUE TITLE
[Feature] Admin - schedule

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#10]
Can we make it so the admin can view the schedule in different formats (view a particular mentors schedule and a particular startup's schedule)? 

I'm guessing this is viewable to the startups and mentors within their apps (haven't gotten there yet), but would be nice from within admin portal as well.

**Comment by greenido** [comment]
Good idea.
If I'll have time - we will have it for the beta version (=this LPA).

**Comment by greenido** [comment]
...and we have this new viewer! 
It gives you the option to watch a daily schedule per mentor or per startup.
Please check, confirm and close this one. Thx!

**Comment by joshyellin** [comment]
Looks great!
