### ISSUE TITLE
[Startup] Schedule not showing up

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#100]
The schedule does not show up for the startup "Yellin Industries". Same month/day/year.

See startup app (after trying to reload a couple times):
<img width="1104" alt="screen shot 2016-12-11 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084358/34289c8e-bfb7-11e6-99c2-daf56720ec3f.png">

And see admin app (set the schedule here a while back and it still shows up... so should show up for startup)
<img width="981" alt="screen shot 2016-12-11 at 3 33 52 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084361/49593190-bfb7-11e6-90ec-21b357ab1930.png">

**Comment by greenido** [comment]
You can see at the admin top-nav bar the status icon with: "Not good... try to reload".
It means you got some issues with firebase - please reload both apps (with clean cache) and see if you can reproduce it.
Try to open chrome devtools and put the output here is you see some errors - thx!

**Comment by joshyellin** [comment]
Cleared all browsing data, re-logged into both apps, same problem.

You can show me how to use chrome devtools and share the output when we're together in Mexico.

**Comment by greenido** [comment]
You are not looking at the right startup... you have two.
Make sure you put the attendee in the right place and you will see the schedule.

**Comment by joshyellin** [comment]
+1

When I added the "1", I forgot that it would duplicate and not simply edit. A good reminder from an Admin perspective... be cautious about creating duplicate accounts when editing profiles.
