### ISSUE TITLE
Mentors details and links

### ISSUE THREAD

**Issue by greenido** [greenido/lpa-1#117]
1. The links to linkedin and other should open a new tab.
2. The current links are not working. We need to handle all the cases of http or the lack of http://
3. Please add more details on the mentors. For example: bio, expertise. You can have these in 'expend' element so it won't break the current list.

See this example for a current links that aren't working.
<img width="577" alt="screen shot 2017-01-18 at 11 45 22 am" src="https://cloud.githubusercontent.com/assets/61472/22080305/f315ab62-dd73-11e6-9e65-a31013e82ab6.png">

**Comment by greenido** [comment]
Any update?

**Comment by devnook** [comment]
It's in progress, I'll try to push it live sometime tomorrow.

**Comment by greenido** [comment]
OK - please make sure to sync as I did quite a few changes to the code.
