### ISSUE TITLE
[Feature] Mentors and startups schedule

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#12]
Would be great if mentors and startups could view their schedule at-a-glance (only startup, time and room... no notes), then click into their specific meeting to add notes to it. Right now it's tough to see and comprehend your full schedule.

opening and collapsing might be best so they don't have to jog back and forth between looking "into" a meeting and looking into the general schedule... I'm not sure, tbh... you prob know best .

**Comment by greenido** [comment]
1. Startup don't have notes only mentors.
2. Mentors - I guess we want 'notes' to be there in order to force them to fill it.
