### ISSUE TITLE
[Bug] Attendee registration from admin

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#13]
It won't let me "save" a new attendee from the admin side. I was able to add a startup, but wasn't able to add an attendee.

**Comment by greenido** [comment]
Please describe the steps you did... so I could reproduce it.
For me - It's working nicely.

**Comment by joshyellin** [comment]
<img width="1248" alt="screen shot 2016-05-04 at 2 08 40 am" src="https://cloud.githubusercontent.com/assets/18670546/15005598/2c0936bc-119d-11e6-8ed7-136e3574fcd2.png">

**Comment by joshyellin** [comment]
I just went there and when I click "save," nothing happens (not even an error message)

**Comment by greenido** [comment]
You are trying it from a new profile in chrome and not the one that you signing to the admin, right?

--from my mobile

**Comment by greenido** [comment]
It's solved in #18
