### ISSUE TITLE
[Bug] Admin - startup and mentor tiles too big

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#15]
Any way we can shrink the size of the startup and mentor tiles (at least from the admin side)? certainly not urgent, but as we get a lot more (over 60 attendees, almost 40 mentors), the list will get really long and it will be hard to see the info at-a-glance.

**Comment by greenido** [comment]
It won't be good from the UX point of view.
But you can always use 'cmd +' or 'cmd -' to shrink the tab with the lists.

Btw, the right solution will be to give you a nice way to filter/search this list - but for now, you can use 'cmd-f' and the browser will search for you.

**Comment by joshyellin** [comment]
Ok, sgtm
