### ISSUE TITLE
[Feature] Mentor profile

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#17]
Fields to add:

Secondary domain (with same dropdown as "domain")
Sector expertise (i.e., education, biotech, banking, enterprise, etc.)
Twitter handle
short bio
fun fact (let's add this for attendees as well)

**Comment by greenido** [comment]
1. Done - please check both in the admin and the mentor apps.
2. I've added all the fields except 'Sector expertise' as you can fill it in the current expertise field.

**Comment by greenido** [comment]
I'm closing this one. please open it if you don't see the fields.
