### ISSUE TITLE
[Bug] Startup app - general

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#19]
When I login as a whitelisted attendee, I am able to login but can't access any info (everything is blank). 

Also, once I'm logged in, I can't log out.

**Comment by greenido** [comment]
1. I've added this functionality. Now, any attendee can update her details.
2. As for the logout issue - please open a separate ticket (only one item per ticket - please! :) with the steps to reproduce. For me it's working...

**Comment by joshyellin** [comment]
Discovered more here... the startup app just won't work with my personal email: josh.yellin@gmail.com.

I'm able to add that email as a startup (which wasn't possible before because of the ".") but it still won't actually show any startups or mentors when I sign in with that email. I'm thinking there is still a problem with the app recognizing that email because of the period. What do you think?

**Comment by joshyellin** [comment]
Also, the logout issue is linked with this issue... emails with periods before the @ seem to be giving the app some trouble.

**Comment by greenido** [comment]
It should be fixed now.
please check, confirm and close this one.

**Comment by joshyellin** [comment]
Yep, fixed.
