### ISSUE TITLE
[bug] Startup login - can't input info

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#2]
When I logged in as a startup, I wasn't able to enter any of my info. It may be that we're not there yet, but I logged in with my google account but couldn't do anything afterward.

**Comment by greenido** [comment]
Have you made sure that as 'startup' (=attendee) is already in the system?
We wish to 'white list' all the participate in advance - so you must enter their name/email/tel and then try to login.

**Comment by greenido** [comment]
@joshyellin is it still an issue?
If not - let's close it.

**Comment by joshyellin** [comment]
Can't test it bc I can't add an attendee (issue on a diff thread). Once I successfully can add an attendee, I'll login from that side on the whitelisted email.

**Comment by greenido** [comment]
Now you can :)
