### ISSUE TITLE
[Feature] Mentor app - tap into startup card

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#20]
Can't tap into startup cards when logged into the mentor app. I would want to tap into a card to access more info (fundraising, "history link"... which will probably be the one pager). All that's valuable stuff.

Think we can do in v1?

**Comment by greenido** [comment]
Will try!!

**Comment by greenido** [comment]
Please check. I've added all the parameter we holding. 
For V1 - The history file should be a link to a google doc...

**Comment by joshyellin** [comment]
Looks great!
