### ISSUE TITLE
[Bug] Startup app - mobile

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#21]
Looks good, but no features or access to info.

**Comment by greenido** [comment]
What do you mean?
The only major function here is to get the schedule.

You should also be able to see a list of mentors and attendees.

**Comment by greenido** [comment]
This is what I get when I'm login in with my 'attendee' gmail account:
![screen shot 2016-05-05 at 9 32 08 am](https://cloud.githubusercontent.com/assets/61472/15037490/549b26d2-12a4-11e6-83c1-3b91f09d16a4.png)

**Comment by joshyellin** [comment]
<img width="1280" alt="screen shot 2016-05-05 at 3 37 11 am" src="https://cloud.githubusercontent.com/assets/18670546/15037568/b5a3f922-1272-11e6-93ec-bedbe56f65b2.png">

**Comment by joshyellin** [comment]
It's glitching a little... won't let me sign out and sign back in. I'll try to restart my machine tomorrow and give it a fresh go.

**Comment by greenido** [comment]
The best will be to open a incognito window each time - so you starting
with clean on each test.

**Comment by greenido** [comment]
btw, it seems that your attendee user doesn't have a name. 
You must have a name and email for each user.

**Comment by joshyellin** [comment]
This issue is being addressed in another ticket.
