### ISSUE TITLE
[feature] Add a way in the admin to add rooms/locations

### ISSUE THREAD

**Issue by greenido** [greenido/lpa-1#22]
1. Name
2. Address
3. Comments

**Comment by greenido** [comment]
Done.
You can now add locations.

**Comment by greenido** [comment]
Please check and close... thx!

**Comment by joshyellin** [comment]
Where do you add the locations?  I see the options in the scheduler, but not sure how to add/edit/remove.

**Comment by greenido** [comment]
Refresh cache and/or start in incognito window.

--from my mobile

**Comment by joshyellin** [comment]
Got it now.  :)
