### ISSUE TITLE
[Bug] Admin - copyedit on error message

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#23]
Error message in scheduler needs slight correction.

Current message:
"Yo! You have assign the same mentor to more then one startup at: 9:00 - 10:00 - Please fix it as we can't split mentors (yet). 
Wanna save it anyway?"

Updated message:
"Yo! You have assigned the same mentor to more than one startup (at least during 9:00 - 10:00). Please resolve this as we can't split mentors (yet). 
Wanna save it anyway?"

**Comment by greenido** [comment]
Cool! 
I'll fix it first thing in the morning 

--from my mobile

**Comment by greenido** [comment]
fixed.
