### ISSUE TITLE
[Feature] Mentor app - impromptu feedback/notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#24]
Paco brought up a good point. Can we add a feature where mentors and startups can add notes/homework/etc. from impromptu meetings, as there will be a lot of unscheduled conversations. 

Most of these won't warrant tracking, but some def will.

Thoughts?

**Comment by greenido** [comment]
Mentors can save 'free' notes today in the history file we got per startup.
This history file will be a google doc for now.

As for attendees - let's talk about it. We can do the same with them.

**Comment by joshyellin** [comment]
Cool. We'll walk through this at next standup meeting

**Comment by greenido** [comment]
Closing this one because for the near future we are going to allow only mentors to use the app for notes.
Attendees should use a trix they share (and we should offer a template for that trix)
