### ISSUE TITLE
[Bug] Admin - mentor enrollment, domain dropdowns

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#26]
We need a (N/A) for secondary domain in the dropdown (some mentors don't have a secondary). 

We also need "other" or "Google Product" or something for both primary and secondary (for example, when we have Googlers mentor toward a specific product).

**Comment by greenido** [comment]
1. It's fixed - please check and close this ticket.
2. Please separate these to 2 tickets in the future.

**Comment by joshyellin** [comment]
Thanks, and noted.
