### ISSUE TITLE
[Bug] Mentor, Startup - Mentor profile view

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#27]
From what I can tell, you can only view mentor profiles from the Admin app. The startups (and mentors) should be able to peruse through the mentor profiles as well. Startups, to prep for their next 1:1 meeting; mentors, for networking and their own interest.

**Comment by greenido** [comment]
You can now see the mentors both on the startup app and on the mentor app.
Please check and close. Thx!

**Comment by joshyellin** [comment]
Looks good!
