### ISSUE TITLE
[Bug] Admin - adding new mentors

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#29]
When adding new mentors, you have to save the previous one, then click "clear," and then not everything clears (twitter, bio, etc.), so you have to manually delete.

_[Ideal scenario - there is an "add new mentor" button; when you click on a mentor you are in "view mode" and can then click the edit button to begin to make changes (right now there is only edit mode).]_ I will move this portion to an "enhancement" ticket.

bare minimum - when you click "clear," everything clears.

**Comment by greenido** [comment]
The ideal is the 'clear' version since it gives what you want.
We need to make sure it's clearing every input field.

**Comment by greenido** [comment]
fixed - please check.

**Comment by joshyellin** [comment]
works
