### ISSUE TITLE
[Enhancement] Admin - mentor scheduling

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#32]
Can we put in the days mentors will be available to mentor and have that reflected on the schedule? For example, we will probably have ~50 mentors in our system, but only ~20-25 helping on any given day. If we can put the days they'll be in the space in their mentor profile and have them only show up on the schedule on those given days, that would be ideal. Better yet, if there was a mentor availability matrix (something like this trix), that would be ideal:

https://docs.google.com/spreadsheets/d/1Qvdu3w6ZXx4bux-7kgWM-NL3U3Mt9hI8tuYPCdYZlPE/edit#gid=912819188

**Comment by greenido** [comment]
Let's keep it for v2 and see if/how we can solve this issue.
