### ISSUE TITLE
[Bug] Admin - mentor domain

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#34]
I think we need to add monetization

We also need to look collectively at all the categories and give them definitions (as it's becoming a little blurry). But at least for now, I think we need to add monetization as folks have defined themselves as such.

**Comment by greenido** [comment]
Before I'm adding anything, let's have a list of categories that we are all happy with.
/cc @RanNachmany

**Comment by greenido** [comment]
Btw, the current domains are: 
- UX
- Tech
- Product
- Marketing
- Business
- Monetization

**Comment by joshyellin** [comment]
- Fundraising (when we have investors come through). 

Many have self-selected this as their primary domain.

**Comment by greenido** [comment]
Done - please check and close.

**Comment by joshyellin** [comment]
Looks good!
