### ISSUE TITLE
[Question] Enrollment - gmail or google email?

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#35]
When I put in google.com email addresses the system says it must be a gmail address....

Can these email addresses be connected to gmail through apps for work or do they need to actually end in @gmail.com?

**Comment by greenido** [comment]
1. For mentors you can have gmail or google.com emails.
2. For attendees - you need their gmail.

**Comment by RanNachmany** [comment]
Why the limitation? The Android app will support both and I think web app
should too. The reason is that attendees that are working in startups will
prefer to use their work email which (in most cases) is a google account.

Ran

**Comment by greenido** [comment]
because if we won't limit it - it might open a can of worms in all the
cases where the email they gave is NOT a google account.
