### ISSUE TITLE
[Enhancement] Admin - attendee profile

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#36]
Can we add "position" for attendees? To put in CEO, CTO, etc.

**Comment by greenido** [comment]
Done.
Please check it in the 3 apps and close this one.

**Comment by joshyellin** [comment]
Looks good! Final tiny adjustment-- text should be: CEO, CTO, etc.
Currently is: 
<img width="257" alt="screen shot 2016-06-05 at 11 10 17 am" src="https://cloud.githubusercontent.com/assets/18670546/15807267/29ad0bb6-2b0e-11e6-8572-1de9c422aba1.png">

**Comment by greenido** [comment]
fixed
