### ISSUE TITLE
[Enhancement] Attendee - notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#37]
Might want to add "notes" for attendees in addition to mentors. We can probably wait til after some upcoming meetings that will determine our data collection strategy, but wanted to flag this before I forgot.

**Comment by greenido** [comment]
These are the questions/notes we wish:
1. Did the mentor listened to you and reasoned his advices? (text)
2. Was the session effective? (slider 1-5)
3. What did you talk about?
4. What are your next steps and action items?

**Comment by joshyellin** [comment]
Some tiny grammatical edits for the first point:
1. Did the mentor listen to you and explain their advice? (slider 1-5)
2. Was the session effective? (slider 1-5)
3. What did you talk about? action items?

**Comment by greenido** [comment]
Done.
Please check it!
