### ISSUE TITLE
[Bug] Mentor app - notes didn't show up for another mentor

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#38]
When I left notes as one mentor (Josh Yellin left notes for Emprego Ligado), it didn't show up for another mentor (Launchpad Accelerator).

**Comment by joshyellin** [comment]
Played around with this--was able to successfully leave a note, but it was only with one of the original fake companies (eat with me). When leaving notes for the new ones, they don't show up.

**Comment by greenido** [comment]
Please put here all the steps you did so I can reproduce it.
When you add a note for the startup - the other mentors should click on 'Notes' button in order to see all the notes that this startup got.

**Comment by joshyellin** [comment]
1) signed in with Josh Yellin
2) went to my schedule
3) selected May 13
4) Left comments on a startup meeting for GetNinjas and Emprego Ligado and clicked save
5) went to startups
6) clicked "notes" for that startup
7) Nothing happened... didn't even say "no notes"
8) This, however, worked with Eat With Me (one of the previously loaded startups)... notes seem to be working with that one.

**Comment by greenido** [comment]
Please try again... I think it's fixed now.

**Comment by joshyellin** [comment]
Yes, it works now. 👍
