### ISSUE TITLE
[Question] Admin - naming mentors

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#39]
When I name a mentor from admin, and then the mentor logs in for the first time, it changes some of the basic info to match their Google profile.

Is this by design or is it doing it automatically by accident?

I'm not sure how big of a problem this is, but it would may create some inconsistencies.

**Comment by greenido** [comment]
It's by design.

--from my mobile

**Comment by joshyellin** [comment]
Cool.
