### ISSUE TITLE
[Bug] Admin - scheduler error message

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#40]
Can we make the error message more robust? 

Right now, everyday there will 1:many content, which means a single mentor will be repeated for all. This will always happen from 9am-10am everyday, and then also at other times.

Right now this returns "repeat mentor from 9am-10am, is that ok?"  I say ok, no problem there. The problem exists when there are other duplicates that may happen on accident. It will no longer call those out. And when there's an accident, it breaks down the mentor schedule and note taking possibilities. 

It would be great if the error message listed all the timeslots with duplicates, not jsut the first one. That way as an admin, I can know when this is actually a problem and then know how to fix it.

Hope that makes sense.

**Comment by greenido** [comment]
You can now see all the errors in one big message.

**Comment by joshyellin** [comment]
looks good!
