### ISSUE TITLE
[Bug] Mentor - saving notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#41]
Right now you can only save notes one at a time... If, for example, you type notes into each note box, then click save when you're done, this will erase all entries except for the one you clicked save for. 

Ideally mentors would do this after each session, but the way it usually works is they'll do a few sessions, find a minute, and then leave notes for all of them. I'm concerned what will happen a lot of time, is they'll leave notes for several meetings, adn then their notes will get erased--> unhappy customers.

Possible solution: Just having one "save" button that saves all their notes.

**Comment by greenido** [comment]
We are going to have a 'save' note per meeting. 
They should click on 'save' after each notes that they are taking.

The notes aren't erased UNLESS you change the schedule...

**Comment by joshyellin** [comment]
The notes won't be erased if they are saved, I agree, but they will be erased if you type in two text boxes, click save for one text box but haven't clicked "save" yet on another. See below, for example. If neither is saved, and then I click save for one, it will erase the other.

This can probably be curbed with coaching ahead of time, but I imagine some others (as I did) will leave notes for a few meetings, and then click save and lose some of their work.

Does that make sense? (sometimes it's hard to type these things out, lol).

<img width="1079" alt="screen shot 2016-05-31 at 8 08 41 am" src="https://cloud.githubusercontent.com/assets/18670546/15679555/3131e682-2707-11e6-86cb-d9edb1b7c64d.png">

**Comment by greenido** [comment]
I've changed the UI so it's now clear you can only save one note at a time.
Please check it out.

**Comment by joshyellin** [comment]
Yes, I think that solves the issue.
