### ISSUE TITLE
[Question] Admin - dApplication video url

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#43]
The startup application videos are not hosted anywhere publicly accessible and some startups don't have one. Should we still include those in the app?  I motion to remove for V1.

**Comment by greenido** [comment]
There are on youtube... and it is a good way for the mentor to learn more about the startups.
Why won't we update it?

**Comment by joshyellin** [comment]
I figured the permissions were tight on most of them. I will see what sort of coverage we have here. Will probably have videos for 15/24 startups or so.

**Comment by greenido** [comment]
1. All the startups should have a video.
2. In all the cases it should be on youtube with permission of 'unlisted' - so anyone with a direct link can view it.

**Comment by joshyellin** [comment]
They don't because not all actually applied through the application. They
were supposed to but not all did. I'll upload the video for those that did,
however.

**Comment by greenido** [comment]
For the ones that don't have one - let's ask them to create one and upload
it.
It's important that the mentors could see this video before the sessions.
