### ISSUE TITLE
[Enhancement] Admin - Team photo

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#46]
We don't have a team photo for most teams. Can team photo just pull from the individual attendee photos once they're assigned to a startup?

**Comment by greenido** [comment]
No.
But let's ask them for a team photo...
Another way will be to take a photo at the start of the Lpa.

--from my mobile

**Comment by joshyellin** [comment]
Yes, I think that's our best bet. We'll have a photographer there as well,
so it shouldn't be hard.

On Sun, Jun 5, 2016 at 10:59 PM, Ido Green notifications@github.com wrote:

> No.
> But let's ask them for a team photo...
> Another way will be to take a photo at the start of the Lpa.
> 
> --from my mobile
> 
> > On Jun 6, 2016, at 04:57, joshyellin notifications@github.com wrote:
> > 
> > We don't have a team photo for most teams. Can team photo just pull from
> > the individual attendee photos once they're assigned to a startup?
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/46#issuecomment-223874716, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0nTt_50AJaYMz2Wrv9pcM4JbnfYfks5qI7dCgaJpZM4Iuggc
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
excellent!
