### ISSUE TITLE
realtime db is not updated when removing a mentoring session for mentor

### ISSUE THREAD

**Issue by RanNachmany** [greenido/lpa-1#47]
To Reproduce:
1. Add mentoring session: Mentor X, Startup Y, time: Z.
2. Click "save" and verify at Firebase DB that this session was added at Firebease ref: sessions->date->mentor-X->hour-z
3. Go back to LPA-1 admin, and assign a different mentor to Startup Y at time Z. (i.e change mentor from X to something else)
4. Click save  and watch the firebase database ref sessions->date->mentor-X->hour-z. It doesn't change. 
Required behavior: database ref sessions->date->mentor-X->hour-z should be deleted.

**Comment by greenido** [comment]
Fixed. 
Please confirm and close this ticket.
