### ISSUE TITLE
Verify that an email belongs to Google Apps domain when whitelisting mentors and attendees. 

### ISSUE THREAD

**Issue by RanNachmany** [greenido/lpa-1#48]
In order to check if an email belong to Google Apps domain, send the following request: https://www.google.com/a/mydomain.com/ServiceLogin
If it is not a Google Apps domain, you'll get an error page saying:
"Google Apps - Server error 
Server error
Sorry, you've reached a login page for a domain that isn't using Google Apps. Please check the web address and try again"

If it is a Google App domain you'll get a login screen. 

The easiest way is to send that http request and check if the response contains "sorry, you've reach a login page..."

**Comment by greenido** [comment]
You can't do it from the web.
See: No 'Access-Control-Allow-Origin'
