### ISSUE TITLE
Mentoring session notes

### ISSUE THREAD

**Issue by RanNachmany** [greenido/lpa-1#49]
Each mentor and startup will answer 4 questions after (hopefully) every session.
**Mentor**
1. (receptive) Did you feel that the startup was open and receptive to hear your feedback and advice? (slidebar from 0 to 5)
2. (effective) Do you think the session was effective? (slide bar 0-5)
3. (notes) What did you talk about? please write down 1 or 2 challenges that you have discussed during the session.
4. (actionItems) Did you give any homeworks? action items the startup needs to follow?

**Comment by greenido** [comment]
@RanNachmany wdyt?
I'm merging 3 and 4 to one text box. It's more effective.
See below:
![localhost-8888-lpa-1-index-mentor html nexus 6p](https://cloud.githubusercontent.com/assets/61472/15893096/47be9820-2d86-11e6-8b0a-8aa6df81626b.png)
