### ISSUE TITLE
[feature v2] Admin - Schedule

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#5]
Can we make it by 30 mins instead of hour? A lot of engagements are only scheduled for 30 mins (e.g., PlayBD quick sessions), plus it allows more flexibility to book 90 min sessions and start activities on the half hour.

**Comment by greenido** [comment]
We could but I suggest we avoid it - it will make your life harder in terms of setting the schedule.
Let's talk about it.

**Comment by joshyellin** [comment]
Ok, sounds good. It proved necessary last time around, at least in the trix. But yes, we can talk about it on Tues stand-up.

**Comment by joshyellin** [comment]
I'm hoping we can discuss this before writing it off

**Comment by greenido** [comment]
I have closed it since it's not something we are going to change for V1.
As for V2 - please open a new ticket with a detailed feature request.
