### ISSUE TITLE
Mentor App - show today's schedule by default. 

### ISSUE THREAD

**Issue by RanNachmany** [greenido/lpa-1#50]
Scenario:
1. Open the mentor web app.
2. Login.
3. You are redirected to the schedule tab, but no date is chosen. Instead of seeing a schedule you see a very nice picture. 
Requited behavior: redirect to the schedule tab and display today's schedule by default.

**Comment by greenido** [comment]
Fixed - please confirm and close.

**Comment by joshyellin** [comment]
confirmed
