### ISSUE TITLE
[Bug] Mentor - login error

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#52]
A slight language issue:

1) Click "sign in" in the mentor app
2) exit out of the allow-or-deny pop-up
3) this pops up
<img width="449" alt="screen shot 2016-06-08 at 9 21 45 am" src="https://cloud.githubusercontent.com/assets/18670546/15902032/cfe1b236-2d5a-11e6-83c4-eddbec8d49df.png">

Language should be:

"Oops... there was a little problem.

Please check again, and try clicking "Allow," cool?

If you still can't login, please check with the organizers."

**Comment by greenido** [comment]
Fixed.
