### ISSUE TITLE
[Bug] Admin - mentor notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#53]
Can't see mentor notes from the admin app. Right now I can only add startups, mentors, and agenda... hoping for complete visibility.

**Comment by greenido** [comment]
Not for V1. Keep it for now.

**Comment by joshyellin** [comment]
Ok, recommend admin use a mentor profile to access the info?

**Comment by greenido** [comment]
Until v2 - yes!

--from my mobile

**Comment by greenido** [comment]
done
