### ISSUE TITLE
[Bug] Admin - schedule deletion

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#55]
I just accidentally deleted the schedule a little too easily.

I selected the date I wanted to pull up (June 13th) and then clicked "save schedule" instead of "reload" and it deleted the entire schedule for June 13th. I can see this happening again.

Can we at least get a message to pop up to say (are you sure you want to save this day's schedule as you see here?) to help prevent this from happening?

**Comment by greenido** [comment]
Fixed.
