### ISSUE TITLE
[Question] Mentor app - notes ad hoc

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#56]
I know you answered this before, but I was thinking about it again and don't think I have a clear understanding... Can mentors leave notes about a startup ad hoc? I don't see a way to do it (and I think we said there wasn't a way) but I may be missing something.

I'm just thinking there will be a lot of mentor sessions that will happen spur of the moment. A lot of mentors that are just going to be swinging by that we may plug in with a startup on the fly. It would be great if they could still leave notes that aren't associated with a planned meeting in the schedule.

Maybe that's V2 and we just hope for 90% coverage with our current plan.

**Comment by greenido** [comment]
1. As a feature it will be to V2 or V3.
2. But you can have it for this beta in two ways:
   a. Create for all the mentors a predefine meeting with each startup on a date that is not part of the LPA. Let's say a week before. This will give each mentor the ability to fill details on each startup. However, you should tell all the mentors about this hack.
   b. The mentor should tell you who they are seeing and you can create for them a meeting on the fly.

**Comment by joshyellin** [comment]
Good hacks to note. Thanks.

switched to "enhancement"
