### ISSUE TITLE
[Question] - Admin app - Startup resources

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#57]
We discussed this before, but I want to revisit. I will need some way to share links to speaker decks with the startups as well as surveys, etc. Doing this via email won't be the right answer.

Last time I created a defjam site to host this, and I can do that again if need be.

If not for V1, I'd love to have a way as admin to post up resources for startups, resources for mentors, and general program announcements (sort of the program homepage).

This can probably be converted to "enhancement" but wanted your thoughts before converting over.

**Comment by greenido** [comment]
Please use the 'comments for the day' feature and let me know.
Thanks!

**Comment by joshyellin** [comment]
That will go to each startup... is there a way to do comments for the day for mentors?

**Comment by greenido** [comment]
Not for V1.

--from my mobile
