### ISSUE TITLE
Support for impromptu meetings

### ISSUE THREAD

**Issue by solsona** [greenido/lpa-1#58]
In my experience, participants of startups (and mentors) will have conversations, outside of the scheduled ones. For instance to review an assignment, offer more information or simply follow up on an specific topic.

It would be enough to let the mentor to add a note from the Startups list, maybe:

[Intro clip] [Notes] **[Add note]**

**Comment by greenido** [comment]
Thanks! We thought about it and we got a solution for that.

@joshyellin we have the 'pre-defined' schedule that I told you about.
Please update the mentors about it.

**Comment by joshyellin** [comment]
@greenido if we set a meeting with a mentor with every startup on a given day to allow for ad hoc notes, then they would have to double down on a time slot (something the app doesn't like). To make it work, they would have to be spread out over a few days... it might become a confusing workaround.

Any ideas on how to streamline it?

**Comment by greenido** [comment]
You do it on a date that is before the LPA.
In this day you adding every mentor to every startup.

--from my mobile

**Comment by joshyellin** [comment]
That's really tricky, though, because you can't have a mentor be in 2 places at once in the app, so you cant just assign them to all the startups in one timeslot (unless that has changed)... and even if you could, you could only schedule 9 mentors per day. We could communicate to each mentor what their particular fake day is, but it will start to get hair.

Sorry for continuing to push on this issue / find a solution, but I think it's important.

**Comment by greenido** [comment]
1. The enforcement is just a suggestion, so you can have more than one mentor per startup.
2. You can take a week (the week before the LPA) and make sure each mentor have 3 days with all the startups. 
3. Let's not forget that if a mentor is just 'bumping' into a startup they can talk with you and you can set a 'normal' time slot - so they can fill it with the correct dates. So 1 and 2 are only to cover the cases where you are not there available to set a meeting 'on the fly'.
- In the future, we will have a better option here.

**Comment by greenido** [comment]
As we spoke, it will be in most (if not all) cases AFTER the mentor had a session with this startup - so we are covered as we wish her to fill notes in the last 'session notes'.
