### ISSUE TITLE
[Enhancement] Mentor and admin - mentor comments for the day

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#59]
Comments for the day for mentors

**Comment by greenido** [comment]
You now have the ability to go to the admin app and add 'comments for the day' per mentor (it's in the bottom of their details). Once you click 'Save' - the mentor will see these notes on her schedule tab.

Please check, confirm and close this ticket.

**Comment by joshyellin** [comment]
Looks good!
