### ISSUE TITLE
[feature v2] Adding an activity to schedule

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#6]
Is there a way the admin can add "activities" which could then be added to the schedule? For example, a morning keynote, fun activities, a tech talk, etc.

Or will the schedule only be to schedule mentoring sessions?

It would be nice to be able to do it for everything if possible. If this needs to be v2.0, let me know.

**Comment by greenido** [comment]
For now it's only for mentors.
We can talk about it for the future versions.

**Comment by joshyellin** [comment]
Sounds good. I can probably workaround this easily enough in V1.

**Comment by greenido** [comment]
Btw, you can do it even now if you create 'mentors' as the activity. Since the key for each mentor is her email - you can put something like: techtalk@room.com and give it a nice name. The attendees will see the name.

**Comment by joshyellin** [comment]
Awesome, that will work just fine.

On Sat, Apr 30, 2016 at 12:19 PM, Ido Green notifications@github.com
wrote:

> Btw, you can do it even now if you create 'mentors' as the activity. Since
> the key for each mentor is her email - you can put something like:
> techtalk@room.com and give it a nice name. The attendees will see the
> name.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/greenido/lpa-1/issues/6#issuecomment-215972837

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by joshyellin** [comment]
looks like I can still do this, but just need to say @google.com
