### ISSUE TITLE
[Bug] All apps - wizard

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#61]
The wizard kicks in on all apps everytime you load each app (but before logging in). So it always thinks its your first time.

Can we make the wizard only kick in after someone logs in, and only after their first time logging in?

**Comment by greenido** [comment]
It's not kicking for me. Please describe in details what is happening to you.

**Comment by joshyellin** [comment]
This was an issue Melina pointed out (and I saw it happening on a screenshare), but it's not repeating for me either.

**Comment by greenido** [comment]
Ok.
Next time, let's try to put the 'steps to reproduce'...
