### ISSUE TITLE
[Bug] Mentor - startup videos

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#64]
Most of the startup videos don't work, although the urls seem to be put in correctly.

**Comment by greenido** [comment]
Make sure it's a YouTube link

--from my mobile

**Comment by joshyellin** [comment]
will it not work if its vimeo?

And I see some of them that are not working have the shortlink (youtu.be)

On Sat, Jun 11, 2016 at 12:41 AM, Ido Green notifications@github.com
wrote:

> Make sure it's a YouTube link
> 
> --from my mobile
> 
> > On Jun 11, 2016, at 10:37, joshyellin notifications@github.com wrote:
> > 
> > Most of the startup videos don't work, although the urls seem to be put
> > in correctly.
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/64#issuecomment-225342684, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0qLOmTeESUIyAn1v9Sh9uCIJ8efoks5qKma5gaJpZM4Izfq0
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
So paste the real YouTube and not the short link.
As for Vimeo - it should work.
In case you see some link that doesn't - please put it in the ticket.

--from my mobile
