### ISSUE TITLE
[Question] Admin - scheduler

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#65]
Had a breakthrough idea with Melina that may be able to solve a lot of the scheduling issues in V1.

For the scheduler, can we remove the time dependency of the schedule? Rather than book by timeslot, can we book by appointment number?  For example, let's say you pull up June 13th... what if instead of timeslots (9-10, 10-11, etc.) it was just Appointment 1, 2, 3, etc? Then I could handle the agenda/schedule outside the app with the projected trix (like last time). That way, whether an appointment was 15 minutes or 30 minutes, or 2 hours (and all of these happened in bootcamp one) they would just be assigned an appointment number and would be assigned in the order they would happen.

I think the power of the app in its current state is the profiles and note taking/viewing/sharing. This takes us light years ahead of last time. However, I am nervous about its rigidity in scheduling. I think, for now, if possible it would be easier to manage the hour-by-hour schedule outside the app with a trix projected on the screen (like last time), but still using the app for everything else--to upload the mentor-mentee appointments to allow for the note taking and tracking.

The big question, however, is can we do this? I have no  idea what this looks like code-wise. It seems simpler to me in principle (we'd be removing the layer of hour-by-hour scheduling), but it's possible it would be a hard change to make.

Please let me know what you think.

**Comment by greenido** [comment]
The idea of time slots is by design.
The limit of an hour is (again) by design and we put a lot of thinking into it.

We can talk about new ideas after this LPA. For this one, please use this schedule and make sure all the mentors/startups got meetings. This is the only way for them to be efficient with the app and to take notes.

--from my mobile

**Comment by joshyellin** [comment]
I hear you, and I understand it was by design. I was proposing we roll that
feature back for the launch (like the chat) and do the hour-by-hour
scheduling outside the app for V1 (but doing all else within it). I'd feel
more comfortable running the event if we did.

Sorry for proposing this idea so late, but only struck upon it yesterday
with Melina.

I'll still make the agenda the old way (in a trix) and project it in the
room as the source of truth (as it will allow everyone to see the big
picture and bring clarity to any confusion in the workarounds). I'm just
concerned that we will be in a position where the attendees have
conflicting information (what the app is telling them and what the primary
schedule is telling them).

If an adjustment here is not possible (as you implied), we will roll with
the current scheduler of course and do our best to utilize the workarounds.

On Sat, Jun 11, 2016 at 3:06 AM, Ido Green notifications@github.com wrote:

> The idea of time slots is by design.
> The limit of an hour is (again) by design and we put a lot of thinking
> into it.
> 
> We can talk about new ideas after this LPA. For this one, please use this
> schedule and make sure all the mentors/startups got meetings. This is the
> only way for them to be efficient with the app and to take notes.
> 
> --from my mobile
> 
> > On Jun 11, 2016, at 11:09, joshyellin notifications@github.com wrote:
> > 
> > Had a breakthrough idea with Melina that may be able to solve a lot of
> > the scheduling issues in V1.
> > 
> > For the scheduler, can we remove the time dependency of the schedule?
> > Rather than book by timeslot, can we book by appointment number? For
> > example, let's say you pull up June 13th... what if instead of timeslots
> > (9-10, 10-11, etc.) it was just Appointment #1, #2, #3, etc? Then I could
> > handle the agenda/schedule outside the app with the projected trix (like
> > last time). That way, whether an appointment was 15 minutes or 30 minutes,
> > or 2 hours (and all of these happened in bootcamp one) they would just be
> > assigned an appointment number and would be assigned in the order they
> > would happen.
> > 
> > I think the power of the app in its current state is the profiles and
> > note taking/viewing/sharing. This takes us light years ahead of last time.
> > However, I am nervous about its rigidity in scheduling. I think, for now,
> > if possible it would be easier to manage the hour-by-hour schedule outside
> > the app with a trix projected on the screen (like last time), but still
> > using the app for everything else--to upload the mentor-mentee appointments
> > to allow for the note taking and tracking.
> > 
> > The big question, however, is can we do this? I have no idea what this
> > looks like code-wise. It seems simpler to me in principle (we'd be removing
> > the layer of hour-by-hour scheduling), but it's possible it would be a hard
> > change to make.
> > 
> > Please let me know what you think.
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/65#issuecomment-225349375, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0tqNFOlOJ6sygsNZQBY78xAiILypks5qKoiKgaJpZM4Izf_1
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
The only way to work with all the apps is by using the current scheduler.
Please use it and don't change anything in that method as it's the core for everything.

I don't understand why a trix is better at this stage but it's not important.
Please use the scheduler of the app.

--from my mobile
