### ISSUE TITLE
[Bug] Video - Emprego Ligado video link

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#66]
Emprego Ligado video link not working. It's a vimeo link, full url, presents this screen:

<img width="612" alt="screen shot 2016-06-11 at 10 13 03 am" src="https://cloud.githubusercontent.com/assets/18670546/15986446/1bd22e8c-2fbd-11e6-931c-236e8d2a404a.png">

**Comment by joshyellin** [comment]
I should mention... while accessing from mentor app

**Comment by joshyellin** [comment]
Same thing with AppProva, which is full youtube link.

I think there's a systemic issue here. This is the case for almost all of the video links.

GetNinjas, Hijup, and IDNTimes are the only ones that work.

**Comment by greenido** [comment]
Please Add the links that are creating the problem in this ticket.

--from my mobile

**Comment by joshyellin** [comment]
www.youtube.com/watch?v=s7WhZe2MBPQ&feature=youtu.be

**Comment by joshyellin** [comment]
www.vimeo.com/152340175

**Comment by joshyellin** [comment]
www.youtube.com/watch?v=FbXjlm2epro

**Comment by greenido** [comment]
Fixed.
