### ISSUE TITLE
[Enhancement] Mentor/startup - link to defjam site

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#69]
Can we have a button that links to the bootcamp website within the app (sort of how you made one that takes you to the mentor guidelines right now)?

Don't have a link yet, but the website will be built today.

**Comment by greenido** [comment]
Put in the ticket all the text you wish to have on the site and I'll put it in the apps.

--from my mobile

**Comment by joshyellin** [comment]
I was going to use it for a few things: creating resource pages for
startups and mentors, hosting the agenda, sharing photo albums.

If we do this directly in the app, how would we update it? can we send you
the content we want inserted in there and you can load it up? Can Admin
update it?

Here was the previous bootcamp site
https://events.withgoogle.com/bootcamp1/ to give you an idea--I'm hoping
to have similar functionality.

On Sun, Jun 12, 2016 at 10:46 AM, Ido Green notifications@github.com
wrote:

> Put in the ticket all the text you wish to have on the site and I'll put
> it in the apps.
> 
> --from my mobile
> 
> > On Jun 12, 2016, at 19:58, joshyellin notifications@github.com wrote:
> > 
> > Can we have a button that links to the bootcamp website within the app
> > (sort of how you made one that takes you to the mentor guidelines right
> > now)?
> > 
> > Don't have a link yet, but the website will be built today.
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/69#issuecomment-225450468, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0pCq_De4oysPR3jB7PsOYZiB11Exks5qLEXYgaJpZM4Iz1bZ
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
In case I would separate the two:
1. The resource page + hosting agenda could (=should) be in the app.
2. The photos should be on the site.

so if you can fill #1 here - I will update both apps with it.

**Comment by joshyellin** [comment]
Sounds good. The speaker decks, etc. will be coming in one day at a time
and will be posted after the talks. Should I email you them as they come
in? What do you suggest?

**Comment by joshyellin** [comment]
Also, note that we basically just linked to the photo album on the site, so this could also go into the app. If we can pull off not having a website (which it sounds like we can), I'd much prefer it.

**Comment by greenido** [comment]
If you need to update it daily - I suggest you create a site and just put a
link to it  in the daily comments.

Next time, I could build a feature that will let you update all this
content from the Admin app.

**Comment by joshyellin** [comment]
Ok, sounds good. Can we at least create a link/button to the defjam site in the app?

**Comment by greenido** [comment]
Sure - add the link to this ticket.
Thx

--from my mobile

**Comment by joshyellin** [comment]
events.withgoogle.com/bootcamp-class-2

**Comment by greenido** [comment]
fixed.

**Comment by joshyellin** [comment]
Awesome. Can we change the name of the button from "LPA Class 2" to "Bootcamp Website"?

LPA is internal term and would be good to know it links to the bootcamp site.

**Comment by greenido** [comment]
Fixed.
