### ISSUE TITLE
[Bug] Admin - saving schedule

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#70]
When there is a duplicate it won't let me save.

1) Set new schedule
2) Click save schedule
3) Click yes to warning ("are you sure you want to save schedule for this day?")
4) Second warning--"You have duplicates, save anyway?"... and at that point it won't let me click ok.

**Comment by greenido** [comment]
I can save duplicates mentors - See the 6/6/2016 - I have there myself for 2 sessions at 9:00-10:00.
Please make sure you refresh you code (cmd+shift+reload).

**Comment by joshyellin** [comment]
Still not working for me. "Joshua Yellin" is a mentor for 2 startups at 9:00AM-10:00AM on 6/13/2016. Yet only one of them (Conekta) shows up for 6/13 in the mentor schedule.

<img width="215" alt="screen shot 2016-06-13 at 12 13 58 am" src="https://cloud.githubusercontent.com/assets/18670546/16013968/373c4698-3144-11e6-898b-cb6a071825e1.png">

<img width="966" alt="screen shot 2016-06-13 at 12 13 45 am" src="https://cloud.githubusercontent.com/assets/18670546/16013978/3c214988-3144-11e6-9373-c5d9e22e5d5b.png">

**Comment by greenido** [comment]
That is by design 

--from my mobile

**Comment by joshyellin** [comment]
Can we change it to allow for this?

Under current constraints, if I book someone for 2x30min sessions (9am-9:30am, 9:30am-10am), they can only take notes for one of them. Even if I make it clear in the mentor and startup notes that there will be 2 sessions, the mentor still won't be able to leave notes on one of those sessions.

**Comment by greenido** [comment]
No. At this point we should not do it.

**Comment by joshyellin** [comment]
If we get to the point where we have to tell startups "ignore the timeslots and pay attention only to the agenda in the trix," will we be able to change it?

It would be a necessary component for my plan B. If it's not possible, I'll rethink alternative strategies.
