### ISSUE TITLE
Entire day schedule got erased.

### ISSUE THREAD

**Issue by RanNachmany** [greenido/lpa-1#71]
Here is the scenario:
1. I logged into LPA Admin -> Schedule view. 
2. Reloaded schedule for June 13 2016.
3 Changed single session window (added one mentoring session for Approve at 10am). 
4. Clicked on "Save Schedule"
5. Got a warning that I am trying to assign the same resource at the same time to more than startup. 
6. Clicked "save"
7. The entire day's schedule was erased. All time slots are now with "n/a"

**Comment by joshyellin** [comment]
Happened to me too a sec ago. Same sequence.

**Comment by greenido** [comment]
It's working for me :/
So:
1. Make sure you update the code (you can verify that you (view source: v0.8 at the bottom of the html).
2. You are on a good connection.

**Comment by joshyellin** [comment]
Have both now. Will reopen if happens again.
