### ISSUE TITLE
[Bug] Mentor - leaving notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#73]
Two complaints from mentors:

while leaving notes for a meeting, it would pop up and say "couldn't find anything for this day."

Then they would have to start over. Happened a few times. Finally they gave up.

I tried to get as much detail on repeating steps, but couldn't get more than this.

**Comment by greenido** [comment]
What is the email of the mentor(s) that had this issue?

--from my mobile

**Comment by RanNachmany** [comment]
Not sure if it is relevant, but when I leave my mentor web app opened, I do
get from time to time these messages.

**Comment by greenido** [comment]
It's because you are removing all the sessions to the mentor that got the web app opened.
That's why I want their email.

**Comment by joshyellin** [comment]
mfmosman@gmail.com

On Tue, Jun 14, 2016 at 11:33 PM, Ido Green notifications@github.com
wrote:

> It's because you are removing all the sessions to the mentor that got the
> web app opened.
> That's why I want their email.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/73#issuecomment-226100126, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0sM27FZa10yDYCatXxNN_3gB0qEgks5qL5zLgaJpZM4I1y3A
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>
