### ISSUE TITLE
[Bug] Admin - Notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#76]
The notes is a little buggy.

Go to a startup, click "see 11-13," and then it is always for BankFacil (not necessarily the app of interest)

**Comment by greenido** [comment]
No idea what are you talking about.
1. Please describe in details what do you see.
2. Add steps to reproduce it. 
3. Screenshots are also helpful.

**Comment by joshyellin** [comment]
1. In admin, go to Notes
2. Click BankFacil
3. Click "Next" at bottom
4. The notes that come up correspond to Aliada (wrong startup)

**Comment by greenido** [comment]
@joshyellin I did the steps and I get ONLY notes of BankFacil.
Please add a screen shot.

**Comment by joshyellin** [comment]
[image: Inline image 1]

On Fri, Jun 17, 2016 at 12:16 AM, Ido Green notifications@github.com
wrote:

> @joshyellin https://github.com/joshyellin I did the steps and I get
> ONLY notes of BankFacil.
> Please add a screen shot.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/greenido/lpa-1/issues/76#issuecomment-226698015, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARzj0qO4hTVbGJf4VzfKxO3GY_XkVTGIks5qMknXgaJpZM4I3jCc
> .

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by joshyellin** [comment]
<img width="794" alt="admin app" src="https://cloud.githubusercontent.com/assets/18670546/16143664/06654aba-3423-11e6-8506-130011921963.png">

**Comment by greenido** [comment]
Please check it again with a new version and if it's solved close this one.
Thanks.

**Comment by joshyellin** [comment]
Yes, solved.
