### ISSUE TITLE
[Question] Admin - notes

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#77]
There are _very_ few notes from startups in the app. Is there a data issue or are almost no startups leaving notes?

Would be good to know from a program communication standpoint.

**Comment by greenido** [comment]
It's not an issue with the app - Attendees are not leaving notes, only a few of them.

I would suggest:
1. Please ask/remind them each morning to do it! 
2. Put a reminder in the 'comments for the day' section.

**Comment by joshyellin** [comment]
sg
