### ISSUE TITLE
Name and link to Mentor profile on Notes

### ISSUE THREAD

**Issue by luisbetancourtco** [greenido/lpa-1#79]
It would be great to know who's the mentor behind a note and as we don't perfectly know each other (Specially names), it would be nice to have a link to the author's profile on the note so we can maybe go and discuss some points...

**Comment by greenido** [comment]
Excellent idea!
Thank you @luis3etancourt - please check it out... It's already in production 👍

**Comment by luisbetancourtco** [comment]
@greenido ¿would it be possible to have the button in a different color depending on the expertise of the mentor? It would be useful to be able to focus on feedback from mentors on your area of expertize!

**Comment by greenido** [comment]
Not sure about the color - but we will find a way to add this information so it will be easier for you.
