### ISSUE TITLE
[bug] Add Intro to all the apps

### ISSUE THREAD

**Issue by greenido** [greenido/lpa-1#8]
Use: http://introjs.com or JoyRide (from Zurb) and make sure we are showing the power of the apps to each audience (admin, mentor, startup).

**Comment by greenido** [comment]
@joshyellin FYI: Mentor app + Attendees app are **done**.

**Comment by joshyellin** [comment]
Hell yes.

On Sun, May 8, 2016 at 8:09 AM, Ido Green notifications@github.com wrote:

> Mentor app is done.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/greenido/lpa-1/issues/8#issuecomment-217709836

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
It's now in all the apps.

**Comment by joshyellin** [comment]
Amazing.
