### ISSUE TITLE
[Bug] Admin - mentors not removed from dropdown after scheduled

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#9]
After scheduling a mentor for a given timeslot, they don't disappear from the dropdown when selecting mentors for other startups. 

This would be valuable and would prevent double booking (an issue we dealt with sometimes during bootcamp 1).

**Comment by greenido** [comment]
They should not be removed. We will create a 'test' feature before save to prevent duplicates.

**Comment by greenido** [comment]
The current version is testing to make sure you assign a mentor to more than one startup in a certain hour. Please check.

**Comment by joshyellin** [comment]
Looks good!

**Comment by joshyellin** [comment]
Ok, so the error message worked, but then it won't resolve itself (aka when I remove the duplicates and re-save, the error message still appears). I then reset the schedule and created again (with no duplicates) and error message appeared yet again and the schedule even reverted to an older version.

**Comment by greenido** [comment]
Please put all the steps to reproduce.

**Comment by joshyellin** [comment]
1. Assigned mentor to 2 startups in same timeslot
2. Clicked "Save Schedule"
3. App produces error message - "Yo! You have assign the same mentor to more then one startup at: 9:00 - 10:00 - Please fix it as we can't split mentors (yet).  Wanna save it anyway?"
4. Changes are then made to resolve this (mentor only in one place at one time)
5. Clicked "Save Schedule"
6. Error message comes up again.

**Comment by greenido** [comment]
The error comes with a different hour, no?
Check and again and please let me know.

**Comment by joshyellin** [comment]
No, not a different hour. It just doesn't resolve the original conflict, even after I change it.

**Comment by greenido** [comment]
It's working for me. So let's try to do it step by step.
1. Make sure you set ALL the mentor per hour.
2. If you leave N-A you will get this error.
3. Do it step by step with the names so I could replicate it.

Thanks.

**Comment by joshyellin** [comment]
Then the issue was with the N-A.

Regarding the N-A, there will be a lot of timeslots where the startup won't be assigned a mentor (free-time, work-time, etc.). What does admin do then?

**Comment by greenido** [comment]
Nothing - It's just a warning.

**Comment by joshyellin** [comment]
Cool. Any way to remove the warning with it's the N-A that provides a
conflict? Because I would want to be warned about other conflicts, but
don't need to be warned about N-A double booking.

On Mon, May 9, 2016 at 5:43 AM, Ido Green notifications@github.com wrote:

> Nothing - It's just a warning.
> 
> On Mon, May 9, 2016 at 2:53 PM, joshyellin notifications@github.com
> wrote:
> 
> > Then the issue was with the N-A.
> > 
> > Regarding the N-A, there will be a lot of timeslots where the startup
> > won't be assigned a mentor (free-time, work-time, etc.). What does admin
> > do
> > then?
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/greenido/lpa-1/issues/9#issuecomment-217844396
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/greenido/lpa-1/issues/9#issuecomment-217853815

## 

Joshua Yellin | Developer Platform | jyellin@google.com | (630) 302-1196
<630-302-1196>

**Comment by greenido** [comment]
The warning on N/A was removed.
Please make sure you don't touch the mentor's details we are using for N/A.

**Comment by joshyellin** [comment]
Copy that
