### ISSUE TITLE
[Mentor] Language fix in mentor wizard

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#90]
In the mentor wizard, change:
"See which startups are part of this LPA" to 
"Learn about the startups in this LPA class" 

<img width="873" alt="screen shot 2016-12-11 at 1 24 10 pm" src="https://cloud.githubusercontent.com/assets/18670546/21083430/754e74d4-bfa5-11e6-8444-73362c0234ba.png">

**Comment by greenido** [comment]
Fixed.
