### ISSUE TITLE
[Admin] Add "Resources" for startups and mentors

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#92]
If we can have a very simple "resources" page for startups and mentors, we could do away with needing a defjam site. I think it would be really valuable and (to my ignorant self) possibly easy to implement. wdyt?

It would just be a place to post links and descriptions to those links... mostly for speaker decks (but also other mentor recommended resources and links to photo albums).

**Comment by greenido** [comment]
You already have this functionality today in the Admin app.

* In the schedule you have a 'comments' for the day - which all the startups/attendees see at the top of their daily schedule.

* For mentors, you can put "Notes For the Mentor" and they will see it in their app.

**Comment by joshyellin** [comment]
Yes, but this would be a permanent place to house resources. This would be different than "daily comments." 

The resources tabs would be a place the startups could dependably go back to reference. I don't know if it makes sense to use the "daily comments" feature for both use cases.

If so, maybe we change the name to "resources?" and use Slack for all daily comments?

**Comment by greenido** [comment]
Resources should be part of the defjem site - so you could control it.
As for daily comments - let's use this functionality AND slack.
