### ISSUE TITLE
[Mentor] Additions to mentor profiles

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#93]
Could we add the following fields to the mentor profiles as they're seen in the mentor app?

- City, Country (should def be there)

- Fun Fact (would be nice to have)

**Comment by greenido** [comment]
Seen where?

**Comment by joshyellin** [comment]
When I look at your profile in the admin app, it has all those fields:

<img width="674" alt="screen shot 2016-12-11 at 3 03 43 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084117/0bc4e2ba-bfb3-11e6-8da2-874218c7a394.png">

When I look at your profile in the mentor app, it's missing them:

<img width="586" alt="screen shot 2016-12-11 at 3 02 17 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084107/f1ce7222-bfb2-11e6-9458-69bdca47c83b.png">

**Comment by greenido** [comment]
Why it's important to see city/country there?
I think we should expose only the most important attributes.

**Comment by joshyellin** [comment]
Mentors are coming in from all over the world.  I think it's relevant and cool to know where they come from ahead of time (culturally, market-wise).

**Comment by greenido** [comment]
@devnook this one is not high priority... just if you have time.

**Comment by greenido** [comment]
btw, in the old app I've added more details.
