### ISSUE TITLE
[Mentor] Language suggestions for notes form

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#94]
Some copy-editing on the notes form.

Suggested:

- Were the attendees open and receptive? (grammar)
- Was the session effective? (1-5)
- What did you talk about?
- What action items did you leave them with?
- "Upload photos here" (for camera button)... makes more sense to me

<img width="856" alt="screen shot 2016-12-11 at 1 56 15 pm" src="https://cloud.githubusercontent.com/assets/18670546/21083725/962fe9e8-bfab-11e6-9889-8b8274018b5a.png">

**Comment by greenido** [comment]
Let's talk about this one.
The only change might be in the first one - but I think we will kill it.

**Comment by joshyellin** [comment]
But what did you "**talked**" about should be "**talk** about"

Other than that and first one (which we'll kill), other issues are matter of preference.

**Comment by greenido** [comment]
done
