### ISSUE TITLE
[Mentor] Notes form button improvements

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#97]
Problems: 

1. **The functionality of the orange button with startup name is unclear** (does it open their profile? their notes? I thought their profile til I clicked it, then when I realized it was notes I was wondering where their profile was)
2. **The functionality of the "open" button is unclear** (you don't know til you are curious enough to click it)
3. **There's no quick way to view the startup profile from the schedule**
4. **The slide bars don't have a relative scale** (aka what does 1 mean and what does 5 mean?)

Suggestions:

1. Rename the orange button with the startup name to "Previous notes" (I would think a button with the startup name would open their profile... see 3 in this list)
2. Rename "Open" to "Write your notes" or "Record your notes" (right now it's not clear to me that you write notes there... you have to be curious enough to click "open")
3. Add another button before the others (or above them) that says the startup's name, and this button should open up their profile.
4. Add the following language to the left and right of the slide bar: 1 (Not at all).... 5 (Very much so)

**Comment by greenido** [comment]
The wording is way to long.
Plus, I do think it is ok for ppl to ask and see...

**Comment by joshyellin** [comment]
We can close this ticket, but I suggest we put the mentor notes process through some user testing.
