### ISSUE TITLE
[Startup] Wizard corrections

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1#99]
1. The first wizard bubble: 

<img width="653" alt="screen shot 2016-12-11 at 3 23 10 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084268/caef3738-bfb5-11e6-8ec6-4ddfca7ef373.png">

- "You the attendee" should be "Your profile"
- "First time **you** here?" should be "First time **you're** here?"
- "Please fill all the details" should be "Please fill in all your profile details"
- "2. Sign in at the top right" ... this isn't necessary because the wizard only pops up once you are signed in. This goes for the mentor app as well.

2. The third wizard bubble:

<img width="656" alt="screen shot 2016-12-11 at 3 24 18 pm" src="https://cloud.githubusercontent.com/assets/18670546/21084281/0b320f50-bfb6-11e6-853e-0ff137ff77ec.png">

- "See which startups are part of this LPA"; suggested change--"Learn about the other LPA startups"

3. The fifth wizard bubble: (correction is in bold)

Attendees
See the other attendees' details. 
Btw, you might want to 'Add to home screen' this app. It will help you get **to** it quicker on your next session!

**Comment by greenido** [comment]
Good one!
Fixed.
